name: Deployment
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Download code from Repo to server
        uses: actions/checkout@v4
        with:
          #optional
          show-progress: 'true'

      - name: Install dependencies
        run: npm install && npm ci

      - name: Lint
        run: echo "Linting..."

      - name: Lint file
        run: npm run lint

      - name: Lint
        run: echo "Linted successfully!!!"

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Download code from Repo to server
        uses: actions/checkout@v4
        with:
          #optional
          show-progress: 'true'

      - name: Install dependencies
        run: npm install && npm ci

      - name: Lint
        run: echo "Running test..."

      - name: Test
        run: npm run test

      - name: Lint
        run: echo "Test ran successfully!!!"

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Download code from Repo to server
        uses: actions/checkout@v4
        with:
          #optional
          show-progress: 'true'

      - name: Install dependencies
        run: npm install && npm ci

      - name: Build project
        run: npm run build

      - name: Deploy
        run: echo "Deploying ..."